var heading = "test";
var body = "Testbody";
var cancel = null;
var accept = null;
var oncancel = null;
var onaccept = null;

var dialog = document.createElement("aside");
dialog.className = "mdc-dialog";
dialog.role = "alertdialog";
var surface = document.createElement("div");
surface.className = "mdc-dialog__surface";
var header = document.createElement("header");
header.className = "mdc-dialog__header";
var h2 = document.createElement("h2");
h2.className = "mdc-dialog__header__title";
var headertext = document.createTextNode(heading);
var section = document.createElement("section");
section.className = "mdc-dialog__body";
var bodytext = document.createTextNode(body);
var footer = document.createElement("footer");
footer.className = "mdc-dialog__footer";
var buttonCancel = document.createElement("button");
buttonCancel.className = "mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--cancel";
buttonCancel.type = "button";
var buttonAccept = document.createElement("button");
buttonAccept.className = "mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--accept";
buttonAccept.type = "button";
var backdrop = document.createElement("div");
backdrop.className = "mdc-dialog__backdrop";
var canceltext = document.createTextNode(cancel);
var accepttext = document.createTextNode(accept);

content.appendChild(dialog);
dialog.appendChild(surface);
surface.appendChild(header);
header.appendChild(h2);
h2.appendChild(headertext);
surface.appendChild(section);
section.appendChild(bodytext);
surface.appendChild(footer);
if (cancel != null) footer.appendChild(buttonCancel);
if (accept != null) footer.appendChild(buttonAccept);
buttonCancel.appendChild(canceltext);
buttonAccept.appendChild(accepttext);
dialog.appendChild(backdrop);
var dialogjs = new window.mdc.dialog.MDCDialog(dialog);
dialogjs.listen('MDCDialog:accept', onaccept);
dialogjs.listen('MDCDialog:cancel', oncancel);
dialogjs.show();