name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - name: Compress dist
      run: tar -cvzf dist.tar.gz index.html public/index.html
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist.tar.gz
  deploy:
    name: Deploy to master
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: dist
    - name: Uncompress
      run: tar -xvzf dist.tar.gz
    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BRANCH: master
        FOLDER: .
        CLEAN: false
